"""Ports that isolate application logic from local storage and model adapters."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Protocol
from uuid import UUID

from memorywaveform_extractor.domain.models import (
    ExtractionJob,
    ExtractionMode,
    ExtractionResult,
    OcrToken,
)

if TYPE_CHECKING:
    from PIL import Image
    from memorywaveform_extractor.infrastructure.images import DecodedImage


class ExtractionService(Protocol):
    def extract(self, image: DecodedImage, mode: ExtractionMode) -> ExtractionResult:
        """Extract one canonical result from a decoded local image."""


class VisionProvider(Protocol):
    def extract(
        self,
        image: bytes,
        schema: dict[str, object],
        context: dict[str, object] | None = None,
    ) -> dict[str, object]:
        """Return a JSON object generated by a local vision-language model."""


class OcrProvider(Protocol):
    def read(self, image: Image.Image) -> list[OcrToken]:
        """Return image-grounded OCR tokens."""


class JobRepository(Protocol):
    def create(self, job: ExtractionJob) -> ExtractionJob:
        """Persist a newly submitted job."""

    def get(self, job_id: UUID) -> ExtractionJob | None:
        """Return a job if its ID is known."""

    def update(self, job: ExtractionJob) -> ExtractionJob:
        """Persist a replacement snapshot for an existing job."""


class ArtifactRepository(Protocol):
    def save_input(self, job_id: UUID, image: DecodedImage) -> Path:
        """Persist a normalized input image."""

    def save_result(self, job_id: UUID, result: ExtractionResult) -> Path:
        """Persist canonical JSON for one completed job."""

    def save_annotated_image(self, job_id: UUID, image: bytes) -> Path:
        """Persist a rendered annotation PNG."""
